<!-- README.md is generated from README.Rmd. Please edit that file -->

---
title: paleosedr README
output: 
  html_document:
    toc: true
---


# paleosedr

<!-- badges: start -->
<!-- badges: end -->

## Installation

You can install the development version of paleosedr from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("allenh1470/paleosedr")
```

# paleosedr Vignette

### Developed by: Hunter Allen

### Date last updated: 4/21/2024

paleosedr is a Rstudio package developed for the NAU's Quaternary Geology and Paleoclimatology laboratory. This package primarily aims to take proxy records developed from lake sediment cores and easily organize data, and visualize records. With this package, beginner to moderate coding experience is required. Many of the functions in this package work in tandem with the geoChronR (https://nickmckay.github.io/GeoChronR/) and lipdR (https://lipd.net) packages developed by Dr. Nick McKay.

In this vignette I will walk you through the basics of getting your data set up and standardized in an Excel (.xlsx) file, transplanting data into the LipD Playground (https://lipd.net/playground), producing an age-depth model, mapping your data and visualizing it. I have laid the document out into a few categories so that you can navigate directly to the needed section.

### Table of Content

  1. **Standardized Data**
  2. **LIPD Playground**
  2. **Age Modeling**
  3. **Plotting Sed. Rate and MAR**
  4. **Plotting Multi-Proxy Records**
  5. **Particle Size Heatmap**

CLEAN VERSION OF PALEO-RECORD EXCEL CHART THAT THIS PACKAGE USES:
https://docs.google.com/spreadsheets/d/1C3n3VkCmDMWb8zgZ9EWSfoYNiRP0ziRI/edit?usp=sharing&ouid=105286369374985387783&rtpof=true&sd=true


